### ISSUE TITLE
New base images

### ISSUE THREAD

**Issue by Nedlinin** [tcardonne/docker-github-runner#16]
Basing on Debian Buster means you don't end up with the newest version of git.

Perhaps basing on bulleyes or sid would be a good thing for providing that.  I've run into a few github actions that use git switch for instance and that isn't available until git >=2.23.0.

Another option would be to have the image compile the newest version similar to https://github.com/myoung34/docker-github-actions-runner/blob/master/Dockerfile.base

**Comment by tcardonne** [comment]
Hello,

I've just released v1.4.0, which contains Git version 2.26.2.
I chose to stay with the stable buster image instead of bullseye for now.
