### ISSUE TITLE
entrypoint.sh question

### ISSUE THREAD

**Issue by jpmolinamatute** [tcardonne/docker-github-runner#21]
Hello there!

I just ran a linter in this script a fixed a couple of very small "warning", I also did a small improvement and I'm about to make a PR for them. However, I have a question 

what's the idea behind these three lines

```
if [[ $1 == "bash" ]]; then
    exec "$@"
fi
```

**Comment by tcardonne** [comment]
Hello,

This is purely a helper for debugging purposes. It allows to bypass the entrypoint more easily than providing the `--entrypoint` option, in my opinion.

**Comment by jpmolinamatute** [comment]
cool! thanks!
