### ISSUE TITLE
Can't docker attach to container

### ISSUE THREAD

**Issue by drewwestrick** [tcardonne/docker-github-runner#28]
I'm trying to do some troubleshooting by attaching to a running docker-github-runner container. Is it possible that the supervisor command is blocking a bash shell from opening when I try to attach? Curious if anyone else has run into this issue.

**Comment by UrosCvijan** [comment]
Did you try to just do an exec? Does that get the job done? 
docker exec -it $CONT_ID /bin/sh

**Comment by drewwestrick** [comment]
Thanks, that did the trick. When I was attaching I think I was attaching to the output of the supervisord command. Doing an exec of /bin/sh or /bin/bash works great. Closing the issue.
