### ISSUE TITLE
Container feature is not supported when runner is already running inside container.

### ISSUE THREAD

**Issue by MaximeWillinger** [tcardonne/docker-github-runner#5]
I get this error when I try to use a custom docker image in my action:

```
   runs-on: self-hosted
    container:
      image: ...
```

The Github runner was launched as following:
```
docker run -it --name my-runner \
    -e RUNNER_NAME=my-runner \
    -e RUNNER_TOKEN=token \
    -e RUNNER_REPOSITORY_URL=https://github.com/... \
    -v /var/run/docker.sock:/var/run/docker.sock \
    tcardonne/github-runner
```

Any idea?

**Comment by tcardonne** [comment]
Hi,

Sorry for the response delay.
I've found your error message in the actions/runner code (https://github.com/actions/runner/blob/6c70d53eead402ba5d53676d6ed649a04e219c9b/src/Runner.Worker/ContainerOperationProvider.cs#L54-L70).

Unfortunately, I don't see any possible workaround to this issue. You can use shell commands and run manually your image with `docker run`.

Best regards,
