### ISSUE TITLE
Runner Versioning for Node16

### ISSUE THREAD

**Issue by 1CoolUsername** [tcardonne/docker-github-runner#53]
-------- Workflow Fail Output --------
Current runner version: '2.273.5'
Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node16' is not supported, use 'docker' or 'node12' instead.')
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)

Last Line --> Error: Fail to load actions/checkout/v3/action.yml

------ Specific Action Details ------

Updated to the node16 runtime by default
This requires a minimum [Actions Runner](https://github.com/actions/runner/releases/tag/v2.285.0) version of v2.285.0 to run, which is by default available in GHES 3.4 or later.
Usage
- uses: actions/checkout@v3

------------- Verify Runner -----------

Would someone verify the Image has not been updated with the minimum runner version noted above as v2.285.0; this Node12 to Node16 started causing issues last week.

I figure the image build is currently an outdated Actions Runner version and tested it when I removed all containers and re-pulled image. 
Same version came back: Current runner version: '2.273.5'

**Comment by 1CoolUsername** [comment]
I built my own image from a cloned repo and the workflow completed successfully; the worrying part is the Current runner version: '2.304.0'. 
What am I missing here? Aside from building it within the specific Host; are the Versions specific to OS?

**Comment by beeb** [comment]
I switched to this maintained image: https://github.com/myoung34/docker-github-actions-runner

**Comment by 1CoolUsername** [comment]
That Repo has the worst SEO; was not able to find it prior to using this one. As mentioned in my prior comment; I built my own Image so until that breaks don't want to swap. Thanks for that repo link.

**Comment by beeb** [comment]
Yeah came in 7 in duckduckgo when searching for "docker self-hosted github runner"
