### ISSUE TITLE
Use the GitHub Actions API to create dynamically a registration token

### ISSUE THREAD

**Issue by tcardonne** [tcardonne/docker-github-runner#9]
The actual behavior is to provide a registration token via the environment variable `RUNNER_TOKEN`. This token can be retrieved from the repository's settings, but this token is only available one hour, which might be a problem is some cases.

We could use the [GitHub Actions API](https://developer.github.com/v3/actions/self_hosted_runners/#create-a-registration-token) to dynamically create this registration token. This API endpoint requires a personal access token, which would be provided via another environment variable (ie, `GITHUB_ACCESS_TOKEN`).

**Comment by missedone** [comment]
somebody implement with `curl` and `jq`:  https://github.com/myoung34/docker-github-actions-runner/blob/master/entrypoint.sh#L9-L26

**Comment by tcardonne** [comment]
Implemented in v1.2.0 🚀
